import { Property, PropertyType } from './types';

export const CITIES = [
  'Casablanca',
  'Marrakech',
  'Rabat',
  'Tanger',
  'Agadir',
  'Fès'
];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Villa Moderne avec Piscine',
    description: 'Une villa spectaculaire située dans le quartier Californie à Casablanca. Finitions haut de gamme et jardin luxuriant.',
    price: 25000,
    type: PropertyType.VILLA,
    rooms: 5,
    bathrooms: 4,
    size: 450,
    location: 'Casablanca',
    imageUrl: 'https://picsum.photos/800/600?random=1',
    featured: true,
  },
  {
    id: '2',
    title: 'Appartement Vue Mer',
    description: 'Superbe appartement meublé avec vue imprenable sur la mer à Tanger. Idéal pour les vacances ou long séjour.',
    price: 8000,
    type: PropertyType.APPARTEMENT,
    rooms: 2,
    bathrooms: 2,
    size: 90,
    location: 'Tanger',
    imageUrl: 'https://picsum.photos/800/600?random=2',
    featured: true,
  },
  {
    id: '3',
    title: 'Riad Traditionnel',
    description: 'Vivez la magie de Marrakech dans ce Riad authentique au cœur de la Médina. Patio intérieur et terrasse.',
    price: 15000,
    type: PropertyType.RIAD,
    rooms: 4,
    bathrooms: 4,
    size: 200,
    location: 'Marrakech',
    imageUrl: 'https://picsum.photos/800/600?random=3',
    featured: true,
  },
  {
    id: '4',
    title: 'Studio Cosy Centre Ville',
    description: 'Studio moderne et lumineux au centre de Rabat (Agdal). Proche de toutes commodités et transports.',
    price: 4500,
    type: PropertyType.STUDIO,
    rooms: 1,
    bathrooms: 1,
    size: 45,
    location: 'Rabat',
    imageUrl: 'https://picsum.photos/800/600?random=4',
    featured: false,
  },
  {
    id: '5',
    title: 'Villa de Luxe Palmeraie',
    description: 'Oasis de calme dans la Palmeraie. Architecture contemporaine, immense piscine et personnel inclus.',
    price: 40000,
    type: PropertyType.VILLA,
    rooms: 6,
    bathrooms: 6,
    size: 800,
    location: 'Marrakech',
    imageUrl: 'https://picsum.photos/800/600?random=5',
    featured: true,
  },
  {
    id: '6',
    title: 'Appartement Haut Standing',
    description: 'Résidence fermée et sécurisée à Bouskoura. Golf à proximité, climatisation centralisée.',
    price: 12000,
    type: PropertyType.APPARTEMENT,
    rooms: 3,
    bathrooms: 2,
    size: 120,
    location: 'Casablanca',
    imageUrl: 'https://picsum.photos/800/600?random=6',
    featured: false,
  },
   {
    id: '7',
    title: 'Bureau Open Space',
    description: 'Espace de travail lumineux à Marina Agadir. Parfait pour startups.',
    price: 6000,
    type: PropertyType.BUREAU,
    rooms: 2,
    bathrooms: 1,
    size: 80,
    location: 'Agadir',
    imageUrl: 'https://picsum.photos/800/600?random=7',
    featured: false,
  },
];
